apiVersion: v1
kind: Service
metadata:
  name: tcp-dns
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: dns-sharing-key
spec:
  loadBalancerIP: 172.17.255.55
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
  selector:
    k8s-app: kube-dns
  type: LoadBalancer