redis:
  fullnameOverride: "redis-cart"
  architecture: standalone
  auth:
    enabled: false
  commonConfiguration: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly no
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
  master:
    resources:
      limits:
        memory: 256Mi
        cpu: 125m
      requests:
        cpu: 70m
        memory: 200Mi
    persistence:
      enabled: false
    kind: Deployment