ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    cert-manager.io/acme-challenge-type: http01
  hosts: 
    - name: chartmuseum.34.134.136.14.nip.io
      path: /
      tls: true
      tlsSecret: chartmuseum.34.134.136.14.nip.io
  ingressClassName: nginx